# Generated by Django 4.1.3 on 2022-11-30 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questao', '0002_alter_opcao_questao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcao',
            name='questao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opcoes', to='questao.questao'),
        ),
    ]
